from . import acquisition
from . import promotion
from . import promotion_stage
from . import hr_job
from . import hr_employee
from . import hr_applicant
from . import hr_attendance
from . import regularization
from . import hr_contract
from . import asset
from . import asset_movement
from . import hr_payslip
from . import sub_city
from . import education
from . import survey_user
from . import work_place
from . import hr_employee_base
from . import hr_employee_family
from . import hr_loan
from . import city
from . import appraisal
